# Generated by Django 5.0.6 on 2024-05-23 04:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('place_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('work_time', models.CharField(max_length=255)),
                ('locations', models.CharField(max_length=255)),
                ('services', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('serving_car_type', models.CharField(max_length=255)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('long_lat', models.CharField(max_length=50)),
            ],
        ),
    ]
