# Generated by Django 5.0.6 on 2024-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrive_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(max_length=60),
        ),
    ]
