# Generated by Django 5.0.6 on 2024-05-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0004_delete_group_delete_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='areacode',
            field=models.CharField(default='', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
