# Generated by Django 5.0.6 on 2024-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0005_alter_user_areacode_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='areacode',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
