# Generated by Django 5.0.6 on 2024-05-27 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(choices=[('Diagnose', 'Diagnose'), ('Oil', 'Oil Change'), ('Engine', 'Engine Repair'), ('Aggregate', 'Which is repairing inside part of the car'), ('Car-Battery', 'Battery change'), ('Parts_of_Car', 'Which is a moving part of the Car'), ('Air_condition', 'Switch Air condition'), ('Com-Diagnose', 'Diagnose which is made by computer'), ('Tire', 'Tire switching or buying a new one'), ('Kuzov', "Working on the car's appearance"), ('Brake', 'Which is changing the Brake or whatever fix it takes'), ('Wash', 'Car washing stuff'), ('parts-selling', 'Buying stuff for car'), ('Car-Trade', 'Buying or selling cars'), ('Car paint', 'Painting the car'), ('Fuel', 'The gasoline'), ('Call-repair', 'Repairing by call'), ('Car loading', 'Take the car and transport it to some place')], max_length=100)),
                ('option_description', models.TextField()),
                ('icon', models.ImageField(upload_to='service_icons/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chart.service')),
            ],
        ),
        migrations.CreateModel(
            name='CostDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_taken', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chart.serviceoption')),
            ],
        ),
    ]
